# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://bc-sep.github.io/website4'
baseurl: ''
title: 'My website'
description: 'This is my new website'
permalink: pretty
logo: "/assets/bcsep_logo.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/
  Members: /members/
  Ongoing Projects: /ongoing_projects/
  Contact Us: /contact/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
